twig:
    default_path: '%kernel.project_dir%/templates'
    # Global variables: https://symfony.com/doc/current/templates.html#global-variables
    globals:
        api_key: '%env(API_KEY)%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
