# prediction:
#     path: /highlandersays/{threshold<\d+>?50}
#     controller: App\Controller\WeatherController::highlanderSays

# guess:
#     path: /highlandersays/{guess}
#     controller: App\Controller\WeatherController::highlanderSaysGuess