GET https://httpbin.org/get?show_env=1
Accept: application/json

### POST
POST https://httpbin.org/post
Content-Type: application/json

{
    "id": 999,
    "value": "content"
}

### Send POST request with body as paramters
POST https://httpbin.org/post
Content-Type: application/x-www-form-urlencoded

id=999&value=content

### DELETE
DELETE https://httpbin.org/delete?id=123
Accept: application/json

### Code from Postman as cURL
curl --location --request DELETE 'https://httpbin.org/delete?id=493'

### Code from Postman as HTTP
DELETE /delete?id=123 HTTP/1.1
Host: httpbin.org