App\Entity\Location:
  properties:
    name:
      - NotBlank:
          message: "Name must not be empty."
          groups: ['new', 'edit']
      - Length:
          min: 2
          max: 35
          minMessage: "Name must be at least {{ limit }} characters long."
          maxMessage: "Name must not be longer than {{ limit }} characters."
          groups: ['new', 'edit']
    countryCode:
      - NotBlank:
          message: "Couuntry code must be {{ limit }} characters long."
          groups: ['new', 'edit']
    latitude:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -90
          max: 90
          notInRangeMessage: "{{ label }} must be between {{ min }} and {{ max }} degrees."
          groups: ['new', 'edit']
      - NotEqualTo:
          value: 0
          groups: ['edit']
    longitude:
      - NotBlank:
          groups: ['new', 'edit']
      - Range:
          min: -180
          max: 180
          notInRangeMessage: "{{ label }} must be between {{ min }} and {{ max }} degrees."
          groups: ['new', 'edit']
      - NotEqualTo:
          value: 0
          groups: ['edit']