controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

weater_prediction:
    path: /weather/highlandersays/{threshold</d+>?50}
    controller: App\Controller\WeatherController::highlanderSays

weater_guess:
    path: weather/highlandersays/{guess}
    controller: App\Controller\WeatherController::highlanderSaysGuess