controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# weater_prediction:
#     path: weather/highlandersays/{threshold}
#     controller: App\Controller\WeatherController::highlanderSays
#     methods: POST|GET